// this file is generated by the build script

import Foundation

enum AnchorVersion {
    static let version: String = "1.9"
    static let build: Int = 94
    #if DEBUG
        static let magical: String = "deadbeef"
    #else
        static let magical: String = "2bae252e029f74d8859cb4b1c57372d5"
    #endif
}
