// this file is generated by the build script

import Foundation

enum AnchorVersion {
    static let version: String = "1.11"
    static let build: Int = 111
    #if DEBUG
        static let magical: String = "deadbeef"
    #else
        static let magical: String = "ec43b199f84a3a9c2347398a5f205be2"
    #endif
}
