// this file is generated by the build script

import Foundation

enum AnchorVersion {
    static let version: String = "1.10"
    static let build: Int = 101
    #if DEBUG
        static let magical: String = "deadbeef"
    #else
        static let magical: String = "620aca918bf4e47fa49c6a0fceefe67c"
    #endif
}
